//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!
package mastermastersql;
import java.awt.*;
import java.awt.event.*;
import java.sql.ResultSet;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.event.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

public class ResultPanel extends JPanel {
    private JTable table;
    private Controller c;
    private TableModel tbm;
    
    public ResultPanel() {
       
    //String data[][] = {{"1.", "ABC"}, {"2.", "DEF"}, {"3.", "GHI" }};
    //String columnNames[] = {"Sr. No", "Name"};
    // DefaultTableModel dfm = new DefaultTableModel(data, columnNames);
    table = new JTable();
    table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
    JScrollPane scrollPane = new JScrollPane(table);
    //scrollPane.setHorizontalScrollBar(new JScrollBar());
    resizeColumnWidth(table);
    
    add(scrollPane);
    }
    public void myModel(ResultSet rs)
     {
             TableModel model = DbUtils.resultSetToTableModel(rs);
             table.setModel(model);
     }

   public void resizeColumnWidth(JTable table) {
    final TableColumnModel columnModel = table.getColumnModel();
        for (int column = 0; column < table.getColumnCount(); column++) {
            int width = 50; // Min width
            for (int row = 0; row < table.getRowCount(); row++) {
                TableCellRenderer renderer = table.getCellRenderer(row, column);
                Component comp = table.prepareRenderer(renderer, row, column);
                width = Math.max(comp.getPreferredSize().width +1 , width);
            }
            columnModel.getColumn(column).setPreferredWidth(width);
        }
}
}
